DoA_QLCuaHangBanDongHo/DoA_QLCuaHangBanDongHo/Controllers/QuanLyLoaiSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.IO;
using DoA_QLCuaHangBanDongHo.Models;
namespace DoA_QLCuaHangBanDongHo.Controllers
{
    public class QuanLyLoaiSPController : Controller
    {
        //
        // GET: /QuanLyLoaiSP/

        QuanLyDongHoDataContext dt = new QuanLyDongHoDataContext();
        public ActionResult QuanLyLoai(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(dt.LOAIs.ToList().OrderBy(n => n.MaLoai).ToPagedList(pageNumber, pageSize));
        }
        //Hien thi san pham
        public ActionResult ChiTietLoai(string id)
        {
            int m = int.Parse(id);
            LOAI loai = dt.LOAIs.SingleOrDefault(n => n.MaLoai == m);
            ViewBag.Masach = loai.MaLoai;
            if (loai == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(loai);
        }
        //Xoa
        [HttpGet]
        public ActionResult XoaLoai(string id)
        {
            int m = int.Parse(id);
            LOAI loai = dt.LOAIs.SingleOrDefault(n => n.MaLoai == m);
            ViewBag.Masach = loai.MaLoai;
            if (loai == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(loai);
        }
        [HttpPost, ActionName("XoaLoai")]
        public ActionResult XacLoai(string id)
        {
            int m = int.Parse(id);
            LOAI loai = dt.LOAIs.SingleOrDefault(n => n.MaLoai == m);
            ViewBag.Masach = loai.MaLoai;
            if (loai == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            dt.LOAIs.DeleteOnSubmit(loai);
            dt.SubmitChanges();
            return RedirectToAction("QuanLyLoai");
        }

        [HttpGet]
        public ActionResult ThemMoiLoai()
        {
            ViewBag.MaNhom = new SelectList(dt.NHOMs.ToList().OrderBy(n => n.TenNhom), "MaNhom", "TenNhom");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoiLoai(LOAI loai)
        {
            //Dua du lieu vao dropdownlist
            ViewBag.MaNhom = new SelectList(dt.NHOMs.ToList().OrderBy(n => n.TenNhom), "MaNhom", "TenNhom");
            dt.LOAIs.InsertOnSubmit(loai);
            dt.SubmitChanges();
            return RedirectToAction("QuanLyLoai");

        }

        [HttpGet]
        public ActionResult ChinhSuaLoai(int id)
        {
            var loai = dt.LOAIs.First(m => m.MaLoai == id);
            ViewBag.MaNhom = new SelectList(dt.NHOMs.ToList().OrderBy(n => n.TenNhom), "MaNhom", "TenNhom", loai.MaNhom);

            return View(loai);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSuaLoai(int id, FormCollection collection)
        {
            ViewBag.MaNhom = new SelectList(dt.NHOMs.ToList().OrderBy(n => n.TenNhom), "MaNhom", "TenNhom");
            var loai = dt.LOAIs.First(m => m.MaLoai == id);
            var loai_Edit = collection["tenloai"];
            //var nhom_Edit = collection["MaNhom"];
            loai.MaNhom = id;

            if (string.IsNullOrEmpty(loai_Edit))
            {
                ViewData["Loi"] = "Tên không được để trống";
            }

            else
            {
                loai.TenLoai = loai_Edit;
                //loai.MaNhom = ViewBag.ma;
                UpdateModel(loai);
                dt.SubmitChanges();
                return RedirectToAction("QuanLyLoai");
            }
            return this.ChinhSuaLoai(id);
        }

    }
}

DoA_QLCuaHangBanDongHo/DoA_QLCuaHangBanDongHo/Views/QuanLyLoaiSP/ChiTietLoai.cshtml
@model DoA_QLCuaHangBanDongHo.Models.LOAI

@{
    ViewBag.Title = "ChiTietLoai";
    Layout = "~/Views/Shared/_LayouDangNhap.cshtml";
}

<h2 style="text-align:center">CHI TIẾT LOẠI</h2>

<fieldset>
    <legend></legend>
<table  class="table table-bordered">
    <tr class="thead-dark" style="text-align:center">
        <th>
                 TÊN LOẠI
        </th>
        <th>
                 TÊN NHÓM
        </th>
    </tr>
    <tr>
        <th>
                @Html.DisplayFor(model => model.TenLoai)
        </th>
        <th>
                @Html.DisplayFor(model => model.NHOM.TenNhom)
        </th>
    </tr>
</table>
    
   

    
   
</fieldset>
<p>
    @Html.ActionLink("TRỞ VỀ ", "QuanLyLoai",null,  new { @class = "btn btn-danger" }) 
</p>

DoA_QLCuaHangBanDongHo/DoA_QLCuaHangBanDongHo/Views/QuanLyLoaiSP/ChinhSuaLoai.cshtml
@model DoA_QLCuaHangBanDongHo.Models.LOAI

@{
    ViewBag.Title = "ChinhSuaLoai";
    Layout = "~/Views/Shared/_LayouDangNhap.cshtml";
}

<h2>CHỈNH SỬA LOẠI</h2>

@using (Html.BeginForm( )) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>

        </legend>

        @Html.HiddenFor(model => model.MaLoai)
        <table class="table">
            <tr>
                <td>TÊN LOẠI: </td>
                <td><p>@Html.TextBox("tenloai") @ViewData["Loi"]</p></td>
            </tr>
            <tr>
                <td>TÊN NHÓM:</td>
                <td>@Html.DropDownList("MaNhom")</td>
            </tr>
        </table>
        <p>
            <input class="btn btn-warning" type="submit" value="Save" /> |
              @Html.ActionLink("TRỞ VỀ ", "QuanLyLoai",null,  new { @class = "btn btn-warning" }) 
        </p>
    </fieldset>
}

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

DoA_QLCuaHangBanDongHo/DoA_QLCuaHangBanDongHo/Views/QuanLyLoaiSP/QuanLyLoai.cshtml
@{
    ViewBag.Title = "QuanLyLoai";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
@using DoA_QLCuaHangBanDongHo.Models
@using PagedList.Mvc;
@model PagedList.PagedList<DoA_QLCuaHangBanDongHo.Models.LOAI>
<h2 style="text-align:center">QUẢN LÝ LOẠI</h2>

<p>
    @Html.ActionLink("THÊM MỚI", "ThemMoiLoai","QuanLyLoaiSP")
</p>
<table class="table table-bordered">
    <tr class="thead-dark" style="text-align:center">
        <th>
           TÊN LOẠI
        </th>
        <th>
            TÊN NHÓM
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr class="table table-striped table-warning">
        <td>
            @Html.DisplayFor(modelItem => item.TenLoai)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NHOM.TenNhom)
        </td>
        <td>
            @Html.ActionLink("Sửa", "ChinhSuaLoai", new { id=item.MaLoai } ,  new { @class = "btn btn-dark" }) |
            @Html.ActionLink("Chi Tiết", "ChiTietLoai", new { id=item.MaLoai },  new { @class = "btn btn-danger" }) |
            @Html.ActionLink("Xóa", "XoaLoai", new { id=item.MaLoai },  new { @class = "btn btn-dark" })
        </td>
    </tr>
}

</table>

@* Tạo liên kết các trang *@
Trang @(Model.PageCount <Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount;
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("QuanLyLoai", new {page=page }))
</div>

<style>
    .MenuTrang li {
        display:inline;
    }
</style>

DoA_QLCuaHangBanDongHo/DoA_QLCuaHangBanDongHo/Views/QuanLyLoaiSP/ThemMoiLoai.cshtml
@model DoA_QLCuaHangBanDongHo.Models.LOAI

@{
    ViewBag.Title = "ThemMoiLoai";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}


<h2 style="text-align:center">THÊM MỚI LOẠI</h2>

@using (Html.BeginForm()) {
   @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
<fieldset>
        <legend></legend>
<table class="table table-bordered">
    <tr>
        <td>
             TÊN LOẠI
        </td>
        <td>
            <div class="editor-field">
                @Html.EditorFor(model => model.TenLoai)
                @Html.ValidationMessageFor(model => model.TenLoai)
            </div>
        </td>
    </tr>
    <tr>
        <td>
              TÊN NHÓM
        </td>
        <td>
             <div class="editor-field">
                 @Html.DropDownList("MaNhom")
            </div>
        </td>
    </tr>
</table>
        <p>
            <input type="submit" value="THÊM" class="btn btn-warning"/> |
             @Html.ActionLink("TRỞ VỀ ", "QuanLyLoai",null,  new { @class = "btn btn-danger" }) 

        </p>
    </fieldset>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

DoA_QLCuaHangBanDongHo/DoA_QLCuaHangBanDongHo/Views/QuanLyLoaiSP/XoaLoai.cshtml
@model DoA_QLCuaHangBanDongHo.Models.LOAI

@{
    ViewBag.Title = "XoaLoai";
    Layout = "~/Views/Shared/_LayouDangNhap.cshtml";
}

<h2 style="text-align:center">XÁC NHẬN THÔNG TIN CẦN XÓA?</h2>
<fieldset>
    <legend></legend>

    <table  class="table table-bordered">
        <tr class="thead-dark" style="text-align:center">
            <th>
                     TÊN LOẠI
            </th>
            <th>
                     TÊN NHÓM
            </th>
        </tr>
        <tr>
            <th>
                    @Html.DisplayFor(model => model.TenLoai)
            </th>
            <th>
                    @Html.DisplayFor(model => model.NHOM.TenNhom)
            </th>
        </tr>
    </table>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="XÓA" class="btn btn-success" /> |
        @Html.ActionLink("TRỞ VỀ ", "QuanLyLoai",null,  new { @class = "btn btn-danger" }) 
    </p>
}